services:
  dev:
    image: kevinnls/node_non-root
    user: node
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - '${NODE_DEV_PORT:-3000}:${NODE_DEV_PORT:-3000}'
    expose:
      - '${NODE_DEV_PORT:-3000}'
    entrypoint: ['npm']
    command: 'run dev -- --host'

volumes:
  node_modules:
